### PR TITLE
Updated appveyor.yml

### PR DESCRIPTION
**Pull request by dedepete**
Fixed AppVeyor CI build.

### CODE REVIEW

**Comment by yakov116** [comment]
LOL appveyor failed

**Comment by dedepete** [comment]
@yakov116 AppVeyor was drunk a bit.

**Comment by yakov116** [comment]
@dedepete are you sure the you arrrrrrrrr nnnnnnnnntttttt dddddrunk LOL

**Comment by yakov116** [comment]
@dedepete it failed again in the revamping_timeline branch

**Pull request merged**
