### PR TITLE
Sidebar enhancement #1405

### PR DESCRIPTION
**Pull request by ShardulKoli**
Added Repos to sidebar as mentioned in issue #1405

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Thanks, but this does exists in menu when u click on profile so I'm not sure what value this could add. I'm thinking of a more general way of adding these to the main active.

**Comment by ShardulKoli** [comment]
This was a active #1405 
So i thought of addressing it that's all.

**Comment by ShardulKoli** [comment]
Also having it on the main sidebar is better in terms of usability as people are not noticing it on the other menu. i think that's why the issue was raised.

**Comment by cozyplanes** [comment]
I think it is redundant. It is there when you click the v button nezt to the top profile. And for the people who don't know this , well, it is their fault

**Comment by k0shk0sh** [comment]
Thanks but as I said, I have another idea of implementing this. 

I'll be implementing this right now :)

**Pull request closed without merging**
