### PR TITLE
Fix for #1832 and #1833 issues

### PR DESCRIPTION
**Pull request by kenrube**

### CODE REVIEW

**Comment by kenrube** [comment]
@k0shk0sh

**Comment by k0shk0sh** [comment]
I don't understand the reason behind doing `page - 1` where it was by default always `0` also, you made the fragments do business logic by doing that behaviour as well, also the app handles screen rotation but not specifically telling the system to kill the activity every single time you start new one. 

besides that i'm working on new FastHub implementation which then will make this redundant.

**Comment by kenrube** [comment]
@k0shk0sh You are right: I didn't explain meaning of fix. Sorry for so late response, I was very busy last time.

Let's say we are at `ProfileStarredFragment` and do some debug of `page` variable.
**1st page**:
- ProfileStarredFragment$onFragmentCreated. `getLoadMore().initialize(getPresenter().getCurrentPage(), getPresenter().getPreviousTotal());`
- ProfileStarredPresenter$getCurrentPage. `page == 0`
- InfiniteScroll$initialize. `currentPage = 0`
- ProfileStarredFragment$onRefresh. `page = 1`
- ProfileStarredPresenter$onCallApi. `page = 1`

**e.g. rotate screen**:
- ProfileStarredFragment$onFragmentCreated. `getLoadMore().initialize(getPresenter().getCurrentPage(), getPresenter().getPreviousTotal());`
- ProfileStarredPresenter$getCurrentPage. `page == 1`
- InfiniteScroll$initialize. `currentPage = 1`

**scroll down to the next page**
- InfiniteScroll$onScrolled. `currentPage++; -> currentPage == 2`
`boolean isCallingApi = onLoadMore(currentPage, totalItemCount);`
- OnLoadMore$onLoadMore. `presenter.onCallApi(page + 1, parameter);`
- ProfileStarredPresenter$onCallApi. `page = 3`
So `page = 3` but should be equal `2` in fact. And so on.

The shortest fix I found is to set initial `page = 1` in presenter and replace `getPresenter().getCurrentPage()` with `getPresenter().getCurrentPage() - 1`. Works fine.

**Comment by kenrube** [comment]
@k0shk0sh Can I close this PR as useless?

**Comment by k0shk0sh** [comment]
Yea, please do so.

Thanks for your time tho

**Comment by kenrube** [comment]
Done. Issues closed too.

**Pull request closed without merging**
