### PR TITLE
annotationProcessor instead of neenbedankt.android-apt

### PR DESCRIPTION
**Pull request by Rainer-Lang**

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Hello Rainer, this pull request will be here until its tested from your side. I'll be updating the contribution guide tomorrow first thing.

**Comment by k0shk0sh** [comment]
@passsy so after pulling this pr, i'm hitting crashes like no tomorrow due to butterknife. 

```
 FATAL EXCEPTION: main
                                                                       Process: com.fastaccess.github, PID: 32656
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fastaccess.github/com.fastaccess.ui.modules.main.MainView}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.setNavigationItemSelectedListener(android.support.design.widget.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.setNavigationItemSelectedListener(android.support.design.widget.NavigationView$OnNavigationItemSelectedListener)' on a null object reference
                                                                           at com.fastaccess.ui.modules.main.MainView.onInit(MainView.java:211)
                                                                           at com.fastaccess.ui.modules.main.MainView.onCreate(MainView.java:95)
                                                                           at android.app.Activity.performCreate(Activity.java:6679)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6176) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 
```

**Comment by passsy** [comment]
😅 haven't tested it, I just found it's code wise correct. You should add Travis builds and some small UI tedts to prevent those problems in the future 😊

**Comment by k0shk0sh** [comment]
@passsy yuup I should, thankfully I made clear build after the second time of running this pr.

**Comment by passsy** [comment]
so it works?

**Comment by k0shk0sh** [comment]
@passsy  Nope, I made clean build and everything starts to crashes lol.

**Pull request merged**
