### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by ptt-homme**
Hi, I translated more than half of the french version. Most important strings are translated, i will adjust and complete it while I'm using it.

Hope this help ;-)

### CODE REVIEW

**Comment by yakov116** [comment]
@ptt-homme Thanks!

your are ready for this to be merged? or you will make more commits?

**Comment by k0shk0sh** [comment]
Better to continue on this rather than merging something unfinished.

Thanks. 

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@ptt-homme thank you so much!

You still have a few more are you able to finish them up?

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 after reviewing this, it appears that the translation is 99.9% done.
@ptt-homme thanks/merci :p

**Comment by k0shk0sh** [comment]
@yakov116 could you add him to the list in readme?

**Comment by yakov116** [comment]
@k0shk0sh done

@ptt-homme thanks

**Comment by ptt-homme** [comment]
@k0shk0sh you're welcome.

Btw, I will check the app when french will be available as language but most of the strings are translated.
Some of them are still in English because tbh I don't know a good way to translate them!

Thanks a lot for this amazing app. Keep on the good work!

**Comment by yakov116** [comment]
@ptt-homme you can get the debug version from appveyor

**Comment by ptt-homme** [comment]
Ths @yakov116 for the trick! Debug app installed, gonna check this we.

**Comment by LSUPERMAN735** [comment]
Maybe I can help you by translating the Readme.md ?

**Pull request merged**
