### PR TITLE
Word replacement (#1430)

### PR DESCRIPTION
**Pull request by TurboProgramming**
See #1430

### CODE REVIEW

**Comment by kutsan** [comment]
Also, thanks for your first contribution to FastHub! We really appreciate it.

**Comment by TurboProgramming** [comment]
@kutsan @k0shk0sh I know why he did it, Google Translate translates Turkish to Türk because Turkish also means Turk. I've seen this on lots of projects, this is not the first. So it's Google's problem.

**Comment by kutsan** [comment]
@TurboProgramming Well, I know that you know the reason why. My explanation was for @k0shk0sh. And I saw [your issue](https://github.com/k0shk0sh/FastHub/issues/1430) afterwards as it is explained by you too.

Also, you can suggest an edit for that translation of Google Translate. IMO very first translation should have been _Türkçe_ as you said. Although, it has approval sign on it, so I don't think they will ever going to change that by a few votes.

**Comment by TurboProgramming** [comment]
@kutsan Yes, I know that. I just said that generally.

Btw, Google Translate is right, Turkish also means Turk and I said that, it should somehow display 2 words at once.

**Comment by TurboProgramming** [comment]
@k0shk0sh I would like to ask something, I opened this PR to push to master, but all other PRs head to the development branch. Did I do wrong targeting master?

**Comment by TurboProgramming** [comment]
@kutsan

**Comment by kutsan** [comment]
@TurboProgramming Well, development branch eventually will have been merged into master for new releases and when things get stable enough to merge in.

There wasn't any problem about your PR since it was only a small change. We can consider it stable. And default branch is development, that's also another reason.

**Comment by TurboProgramming** [comment]
So I should be using the development branch for future changes, right?

**Comment by kutsan** [comment]
Yes, and ping me later in future if you need help, Kosh does seem busy.

**Comment by TurboProgramming** [comment]
OK, thank you @kutsan.

**Pull request merged**
