### PR TITLE
Recompress PNG images losslessly with zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
14 images optimized as below to save some resources!
```
 app/src/debug/res/mipmap-hdpi/ic_launcher.png                  | Bin 5886 -> 5268 bytes
 app/src/debug/res/mipmap-mdpi/ic_launcher.png                  | Bin 3391 -> 3050 bytes
 app/src/debug/res/mipmap-xhdpi/ic_launcher.png                 | Bin 8922 -> 7926 bytes
 app/src/debug/res/mipmap-xxhdpi/ic_launcher.png                | Bin 16815 -> 14547 bytes
 app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png               | Bin 26362 -> 22123 bytes
 app/src/main/res/drawable-nodpi/web_hi_res_512.png             | Bin 121788 -> 104156 bytes
 app/src/main/res/drawable-xxxhdpi/ic_edittext.9.png            | Bin 4333 -> 3971 bytes
 app/src/main/res/drawable-xxxhdpi/ic_timeline_arrow_left.9.png | Bin 1606 -> 1517 bytes
 app/src/main/res/mipmap-hdpi/ic_launcher.png                   | Bin 6540 -> 6022 bytes
 app/src/main/res/mipmap-mdpi/ic_launcher.png                   | Bin 3948 -> 3550 bytes
 app/src/main/res/mipmap-nodpi/foreground.png                   | Bin 99994 -> 86308 bytes
 app/src/main/res/mipmap-xhdpi/ic_launcher.png                  | Bin 9993 -> 9012 bytes
 app/src/main/res/mipmap-xxhdpi/ic_launcher.png                 | Bin 19188 -> 16414 bytes
 app/src/main/res/mipmap-xxxhdpi/ic_launcher.png                | Bin 29389 -> 24634 bytes
```

### CODE REVIEW

**Comment by k0shk0sh** [comment]
could you tell me how much space did you save exactly in total? as I don't think its necessary to do this!

**Comment by dedepete** [comment]
I can see minor differences in colours between images.

**Comment by dedepete** [comment]
Was saved about 49657 bytes (less than 0.1 mb).

**Comment by dedepete** [comment]
@PeterDaveHello coloured only. 
default

**Comment by k0shk0sh** [comment]
Thanks for the PR but I don't think this make any difference.

**Comment by PeterDaveHello** [comment]
Thanks.

**Pull request closed without merging**
