### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by dedepete**

### CODE REVIEW

**Comment by k0shk0sh** [comment]
@dedepete i'm not really sure tho, but in my slack I have a private channel that notify me when builds are done, however i'm keeping receiving your builds since #1 to #116 :D do you have any idea why i'm receiving them even tho they aren't in my repo?

**Comment by dedepete** [comment]
@k0shk0sh oops. I should comment it out.

> .travis.yml
> ```yml
> notifications:
>     **slack: fasthub:mjJWGD8UpgSgKawKa5OqMNlR**
>     email: false
> ```
What a shame. :sweat:

**Comment by k0shk0sh** [comment]
@dedepete no shame at all :D . thank god email was turned off :p .

**Comment by dedepete** [comment]
@k0shk0sh I'm just looking through the issue #423 and it looks like I made a really BIG progress.
image

**Comment by k0shk0sh** [comment]
@dedepete wow, that a really big effort mate 👍  thanks can't wait :D

**Comment by yakov116** [comment]
@k0shk0sh wow!!

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@dedepete wow!

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dedepete** [comment]
@k0shk0sh where are output APK files located? I have difficulties in finding out.

**Comment by k0shk0sh** [comment]
if debug, they will be located at 
```
app/build/outputs/apk/debug
```
if release 
```
app/build/outputs/apk/release
```

**Comment by dedepete** [comment]
@k0shk0sh thank you!

**Comment by k0shk0sh** [comment]
@dedepete anytime buddy :)

**Comment by dedepete** [comment]
And here it is: https://ci.appveyor.com/project/dedepete/fasthub/build/artifacts
I'll make a PR when I clean up the history.

**Comment by yakov116** [comment]
@dedepete you did it!!!

**Pull request merged**
