### PR TITLE
Goodbye F-Droid.

### PR DESCRIPTION
**Pull request by JediBurrell**
Though F-Droid has been a requested platform release for a while, we've made the unanimous decision to drop support for F-Droid. F-Droid does not allow Google libraries, ads, or analytics. And because FastHub relies on a private database ( GitHub ), it's considered to contain "Non-Free Network Services".

This slows down development, causes unknown crashes, and doesn't allow users to support development by enabling ads. This decision came into place when implementing a feature that relied on a proprietary library, it took two days to finally come to the conclusion to drop F-Droid, in this period, I got next to nothing done. And as Android updates, and Google creates new requirements, to add new features, these situations will continue to come up.

F-Droid relies on a private database, and is the one shaming FastHub for doing the same. With this, F-Droid will no longer be supported from May 23rd, 2017. With that, here's the changelog:

* Remove F-Droid support
* Update Profile Layout

I apologize for this inconvenience, you can continue to use F-Droid separate from Google Play, by downloading the releases on this GitHub repository.

### CODE REVIEW

**Comment by thermatk** [comment]
The text justification makes no sense to me. The flavors are easy to use, if you've ever understood the concept once: just copy files with methods you implemented in gms to fdroid and clean them up, so that they don't have to import bad classes.
I've put even more than two days into this, but now that it was done I can't believe it was sooooooo difficult to figure out.
Sorry for not being nice, but I'm angry. 
@k0shk0sh, this is not the way to lead a project, I wasn't even mentioned on github or slack once, so I would get an email notification about your struggles.

**Comment by JediBurrell** [comment]
@thermatk I completely understand, and definitely should have messaged you when we voted against this. This is completely my fault. While the workaround was easy, and yes, I was aware how we could circumvent the issue; we agreed that this was terrible organization and was hesitant of duplicating such large files.

I and @k0shk0sh are very appreciative of the effort you have put forth towards this, and I am sorry that it has been removed. But I really feel that FastHub will greatly benefit from this change.

Backlash was expected, there's no need to apologize, you of all people deserve to complain.

Again, I'm sorry about this change, and assume complete responsibility. People can continue to use it, and update it without Play Services through GitHub releases.

**Comment by thermatk** [comment]
Goodbye Fasthub
You may remove the write access for the repo and slack as I have nothing to maintain
For anyone searching for a replacement - next release of OctoDroid will return to f-droid with my help 🙌

**Comment by k0shk0sh** [comment]
@thermatk sad to see you going but that's your decision and can't hold you from it.
Thanks Ruslan for everything 😉

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
