### PR TITLE
Update sdks

### PR DESCRIPTION
**Pull request by jonathan-caryl**
I noticed there are a few SDKs not up-to-date in the project. Thought I'd update a couple of them that don't require any code changes. Hope that's ok!

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Cool, Thanks Jonathan, I'll be accepting this PullRequest tomorrow after work.

**Comment by k0shk0sh** [comment]
sorry to buzz you, but I need to test something so, please ignore this comment.
#70

**Comment by k0shk0sh** [comment]
Alright @jonathan-caryl  I've merged this pull request, however i'll be dropping `com.github.ben-manes.versions` as of Android 2.0 project structure, they have this functionality plus an update for each library. thanks

**Comment by jonathan-caryl** [comment]
cool

**Pull request merged**
