### PR TITLE
Translated new Strings & updated some strings

### PR DESCRIPTION
**Pull request by failex234**

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Hey Felix, please ignore the failed building, 
`gradle-alpha7` isn't out yet.

**Comment by failex234** [comment]
No, It's not about gradle since it's out. It's about a '&' in the values-de file. Do I have to escape the & ?

**Comment by k0shk0sh** [comment]
Owh is it? didn't see reason tho & yes you should escape it with `&amp;`

**Comment by failex234** [comment]
can I add commits to a non-merged pr?

**Comment by k0shk0sh** [comment]
yup, you can, just edit it from your local and commit, it will be listed here.

**Comment by failex234** [comment]
alright, thank you!

**Comment by failex234** [comment]
But i think that the build will fail again, this time because of the values-it and some apostrophes.

**Comment by failex234** [comment]
yep :P

**Comment by k0shk0sh** [comment]
Oops, could you please merge latest which I just committed which fixes the italian translation escaping.

**Comment by k0shk0sh** [comment]
Thanks Felix :)

**Comment by k0shk0sh** [comment]
Please ignore these tests Felix.

**Pull request merged**
