### PR TITLE
fixes #787

### LINKED ISSUE #787: 进入有问题
**FastHub Version: 4.0.2**  
**Android Version: 7.0 (SDK: 24)**  
**Device Information:**  
- MANUFACTURER: HUAWEI
- BRAND: HONOR  
- MODEL: NEM-AL10  
---

 有时候会出现进入不了应用的情况

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 HONOR NEM-AL10 发送_

### PR DESCRIPTION
**Pull request by yakov116**
adds a notice if the land is not english that request ahould be in english

### CODE REVIEW

**Comment by k0shk0sh** [comment]
why does this need to be in the Issue template & not a warning before submitting the issue? I don't see that we need to add this to the template & it doesn't add anything but adding things we don't want to see. 

the best for this to be added is as dialog in here 
https://github.com/k0shk0sh/FastHub/blob/0d6368b3fb13e6db54c2e2e9ec282611a5255348/app/src/main/java/com/fastaccess/ui/modules/repos/issues/create/CreateIssueActivity.java#L233-L233

**Comment by yakov116** [comment]
@k0shk0sh it does not show in the template the line will be ignore

**Comment by k0shk0sh** [comment]
@yakov116  it doesn't matter, it's still the same, user will ignore it since its not something that will caught their eyes. 

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh I think it will be good since it was the only issue we ever had that was not in english o this will be enough

**Comment by k0shk0sh** [comment]
@yakov116  alright, I'm convinced in a second thought

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
