### PR TITLE
Arabic translation

### PR DESCRIPTION
**Pull request by akkk33**

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Nice despite I'm from Libya and my native language is Arabic, I couldn't translate the app to it 😂. I like what you did.

Thanks buddy

**Comment by akkk33** [comment]
Wow ! I'm Egyptian , and I'm facing the same problem with my apps , I feel lazy to translate them to Arabic 😂 . 
Welcome to the club

**Comment by akkk33** [comment]
Done ... I've just removed them .
Should I make a pull request again ?

**Comment by dedepete** [comment]
No worries, if you commit the changes into the branch you want to merge, the pull request will be updated automatically.

**Pull request closed without merging**
