### PR TITLE
Improved Russian translation

### PR DESCRIPTION
**Pull request by dedepete**
It would be better to merge this Pull Request right before the release so the translation will be up-to-date.

### CODE REVIEW

**Comment by yakov116** [comment]
@dedepete thanks

**Comment by dedepete** [comment]
> It would be better to merge this Pull Request right before the release so the translation will be up-to-date.

¯\\\_(ツ)\_/¯

**Comment by yakov116** [comment]
@dedepete

**Comment by k0shk0sh** [comment]
@yakov116 don't be so harsh.

_Sent from my Galaxy S8 using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh LOL look it says edited. somehow I by mistake (2 times) hit comment. its missing the `lol` at the end LOL

**Pull request merged**
