### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by Rintan**

### CODE REVIEW

**Comment by Rintan** [comment]
What's the matter? I can't guess it...

**Comment by k0shk0sh** [comment]
@Rintan nothing wrong, travis wasn't able to find the build tools. 

thanks for the PR.

**Comment by k0shk0sh** [comment]
@yakov116 could you please add him to the language contribution list & also in your XDA thread? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@k0shk0sh its been done! @Rintan Thanks

**Pull request merged**
