### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by dedepete**

### CODE REVIEW

**Comment by yakov116** [comment]
@dedepete want to push your appveyor changes too?

**Comment by dedepete** [comment]
@yakov116 not from this branch.

_Отправлено с моего YotaPhone YD201 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k0shk0sh** [comment]
@yakov116 it fails because of me. so wait until i merge & push from my side.

**Comment by yakov116** [comment]
@k0shk0sh signing config?

**Comment by k0shk0sh** [comment]
@yakov116 yeep :)

**Comment by k0shk0sh** [comment]
ok its fixed now :)

**Pull request merged**
