### PR TITLE
New Traditional Chinese translation

### PR DESCRIPTION
**Pull request by maple3142**
in res/values-zh-rTW

### CODE REVIEW

**Comment by k0shk0sh** [comment]
hey @maple3142 thank you very much mate :) 

could you please while at it, add the language to https://github.com/k0shk0sh/FastHub/blob/bbed8056ee65fddc0b2f06d017424e200f3903f4/app/src/main/res/values/arrays.xml#L129-L129 
and https://github.com/k0shk0sh/FastHub/blob/bbed8056ee65fddc0b2f06d017424e200f3903f4/app/src/main/res/values/arrays.xml#L117-L117

**Comment by k0shk0sh** [comment]
@maple3142 that was sooo quick, thank you very much :)

**Comment by k0shk0sh** [comment]
@yakov116 you might wanna get his xda developer account :p

**Comment by yakov116** [comment]
@maple3142 you have an XDA account?

**Comment by maple3142** [comment]
@yakov116 yes
[https://forum.xda-developers.com/member.php?u=8235628](https://forum.xda-developers.com/member.php?u=8235628)

**Comment by k0shk0sh** [comment]
@maple3142 when I ran the app and select the language, the only language that doesn't change among the others is this one :D soo confusing

**Comment by maple3142** [comment]
@k0shk0sh I keep all translatable="false" strings in the strings.xml, should I remove them?
[https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/res/values-zh-rTW/strings.xml](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/res/values-zh-rTW/strings.xml)

**Comment by k0shk0sh** [comment]
@maple3142 I already removed them from my side, didn't wanna bother u on it :) & I got it fixed,

apparently,  any language that has `-` should be split, below fix it :D 

```
Locale locale;
        String[] split = language.split("-");
        if (split.length > 1) {
            locale = new Locale(split[0], split[1]);
        } else {
            locale = new Locale(language);
        }
```

**Comment by maple3142** [comment]
I choose "traditional chinese" option in language settings.
But It display simplified chinese(_zh_ ), not traditional chinese(_zh-rTW_ ).
Maybe when you `new Locale()` need to remove `r`  in `rTW`

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi Redmi Note 4 发送_

**Comment by k0shk0sh** [comment]
@maple3142 I don't think I need to remove it and can't know which was selected until I get to my laptop, will do this later. 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by maple3142** [comment]
I use _App Settings(Xposed)_ to force set language to zh-rTW work perfectly.
But built in language selection still not working.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 從我的 Xiaomi Redmi Note 4 發送_

**Pull request merged**
