### PR TITLE
[WIP] webview->textview for comments

### PR DESCRIPTION
**Pull request by thermatk**
Just laying the ground work for the big migration I propose.
But it's so blazing fast! :+1: 
Some bugs might exist due to differences between webview and textview APIs and behaviour, also it might be possible and beneficial to continue replacing some more webviews around with the faster and better predictable textviews :lollipop:

### CODE REVIEW

**Comment by k0shk0sh** [comment]
```
public void setHtml(@NonNull String html, @Nullable ImageGetter imageGetter) {
        HtmlTagHandler htmlTagHandler = new HtmlTagHandler(this.getPaint());
        htmlTagHandler.setClickableTableSpan(this.clickableTableSpan);
        htmlTagHandler.setDrawTableLinkSpan(this.drawTableLinkSpan);
        html = htmlTagHandler.overrideTags(html);
        if(this.removeFromHtmlSpace) {
            this.setText(removeHtmlBottomPadding(Html.fromHtml(html, imageGetter, htmlTagHandler)));
        } else {
            this.setText(Html.fromHtml(html, imageGetter, htmlTagHandler));
        }

        this.setMovementMethod(LocalLinkMovementMethod.getInstance());
    }
```

testing code highlighting.

**Comment by k0shk0sh** [comment]
```
public void setHtml(@NonNull String html, @Nullable ImageGetter imageGetter) {
        HtmlTagHandler htmlTagHandler = new HtmlTagHandler(this.getPaint());
        htmlTagHandler.setClickableTableSpan(this.clickableTableSpan);
        htmlTagHandler.setDrawTableLinkSpan(this.drawTableLinkSpan);
        html = htmlTagHandler.overrideTags(html);
        if(this.removeFromHtmlSpace) {
            this.setText(removeHtmlBottomPadding(Html.fromHtml(html, imageGetter, htmlTagHandler)));
        } else {
            this.setText(Html.fromHtml(html, imageGetter, htmlTagHandler));
        }

        this.setMovementMethod(LocalLinkMovementMethod.getInstance());
    }
```

**Comment by k0shk0sh** [comment]
code highlighting does not work :'( even in this https://github.com/NightWhistler/HtmlSpanner

**Comment by k0shk0sh** [comment]
I guess we should go with `htmlSpanner` due to the fact that it supports CSS, custom handlers which I played around yesterday and we could modify how spans could look and whatsoever.

**Comment by k0shk0sh** [comment]
```
@Override public void handleTagNode(TagNode node, SpannableStringBuilder builder, int start, int end) {
                StringBuffer buffer = new StringBuffer();
                getPlainText(buffer, node);
                builder.append(buffer.toString());
                builder.setSpan(SpannableBuilder.builder().background(buffer, Color.LTGRAY), start, builder.length(), 33);
                this.appendNewLine(builder);
                this.appendNewLine(builder);
            }
```

**Comment by k0shk0sh** [comment]
```
if (loadedImage != null) {
    int width = loadedImage.getWidth();
    int height = loadedImage.getHeight();
    Drawable result = new BitmapDrawable(textView.getResources(), loadedImage);
    result.setBounds(0, 0, width / 2, height / 2);
    builder.setSpan(new ImageSpan(result), start, builder.length(), SPAN_EXCLUSIVE_EXCLUSIVE);
}
```

**Comment by thermatk** [comment]
Please don't use htmlspanner, it's abandoned :(
It should be easier to add code highlighting to a project which is alive

**Comment by k0shk0sh** [comment]
@thermatk well, seeing that project you included I can't see anything that we could do but to modify the whole library itself, the htmlSpanner so far, has zero issues with me, I have added code highlighting to it, images and still i'll be adding more as soon as I notice something, if you are welling to do that, go ahead but until then, i'll continue to use htmlspanner.

**Comment by thermatk** [comment]
With the abandoned one, you'll have to support it yourself, so you can just as well import the whole code now. The htmltextview accept and welcome patches, I would expect it to be more future proof.
Whatever works, first step is to kill the webview :)

**Comment by k0shk0sh** [comment]
@thermatk with that library we have to literally modify the whole base code, but with the htmlspanner despite the fact its abandoned, still works great and easy to modify.

**Comment by thermatk** [comment]
@k0shk0sh cool, just don't merge the whole htmlspanner library as a subproject, because it's not maintainable :) one of its dependencies is completely dead, with jars gone from the servers, etc.

**Comment by k0shk0sh** [comment]
### Ignore this: 

```
if (loadedImage != null) {
    int width = loadedImage.getWidth();
    int height = loadedImage.getHeight();
    Drawable result = new BitmapDrawable(textView.getResources(), loadedImage);
    result.setBounds(0, 0, width / 2, height / 2);
    builder.setSpan(new ImageSpan(result), start, builder.length(), SPAN_EXCLUSIVE_EXCLUSIVE);
}
```

**Comment by k0shk0sh** [comment]
```
if (loadedImage != null) {
    int width = loadedImage.getWidth();
    int height = loadedImage.getHeight();
    Drawable result = new BitmapDrawable(textView.getResources(), loadedImage);
    result.setBounds(0, 0, width / 2, height / 2);
    builder.setSpan(new ImageSpan(result), start, builder.length(), SPAN_EXCLUSIVE_EXCLUSIVE);
}
```

**Comment by k0shk0sh** [comment]
Here you go, with less effort

**Comment by thermatk** [comment]
I see you traded tables, which were somehow working in my version, for code tags :)

**Pull request closed without merging**
