### PR TITLE
Dependencies management with plugin "gradle-kotlin-dsl-libs"

### PR DESCRIPTION
**Pull request by jmfayard**
Apply my plugin https://github.com/jmfayard/gradle-kotlin-dsl-libs

Run `$ ./gradlew syncLibs`

Migrate app/build.gradle to use the syntax
  `implementation Libs.appcompat_v7`

Run again `$ ./gradlew syncLibs`
any time you want to check if there are new dependencies updates
then edit
  `buildSrc/src/main/kotlin/Versions.kt`

Enjoy the benefits of the integration of Kotlin in IntelliJ & Android Studio

See my article
https://blog.kotlin-academy.com/gradle-kotlin-the-missing-piece-of-the-puzzle-7528a85f0d2c

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Thanks for the PR, but currently development has no longer any dev plans. 

Everything right now is being done in V5 branch which has more proper way of handling dependencies.

**Comment by jmfayard** [comment]
@k0shk0sh no problem, kotlinpoet generated the code, not me :)
I see, you are doing that with the dependencies.gradle pattern. 
What do you do to check if newer version of the libraries are available?

**Comment by k0shk0sh** [comment]
I use AS project structure or AS lint.

**Comment by jmfayard** [comment]
@k0shk0sh 
my project is basically the dependencies.gradle pattern, but auto-generated + much better lookup for newer versions + better integration in the IDE. 
I find it's an improvement over how we currently do dependencies, but I'm obviously biased :)

**Comment by mannerav** [comment]
#pullfile

**Comment by jmfayard** [comment]
@k0shk0sh my PR is obsolete, but if interested, have a look at https://github.com/jmfayard/buildSrcVersions

**Pull request closed without merging**
