### PR TITLE
[MERGE READY] Korean translation update for changes made in 4.4.0

### PR DESCRIPTION
**Pull request by cozyplanes**
**MERGE READY**
Korean translation update for changes made in `4.4.0`.
Changes complete `4 out of 4 (4/4)`

### CODE REVIEW

**Comment by k0shk0sh** [comment]
so I'll wait until its 4/4 :p

**Comment by yakov116** [comment]
@cozyplanes you need to fix the `</string> at the end

**Comment by cozyplanes** [comment]
@yakov116 ok

**Comment by k0shk0sh** [comment]
push your commits to this!

**Comment by cozyplanes** [comment]
@k0shk0sh as a github newbie (compared to others) sorry. How do i push commit to this pr?

**Comment by k0shk0sh** [comment]
how do you edit the file?

**Comment by cozyplanes** [comment]
sorry, i do in the web version. sry for the confusion

**Comment by cozyplanes** [comment]
@k0shk0sh finally

**Pull request merged**
