### PR TITLE
multidex is built-in for sdk 21+

### PR DESCRIPTION
**Pull request by thermatk**
There is no need for support multidex, as minsdk is set to 21+

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Strangely, Android studio won't let me build without it? did it build with you?

**Comment by thermatk** [comment]
image
https://developer.android.com/studio/build/multidex.html

**Comment by thermatk** [comment]
Let's see what CI does :)

**Comment by k0shk0sh** [comment]
Yup, I'm waiting for it :D too. 
Strangely last time I got the error that I exceeded the method count & therefore I had to include the multidex.

**Comment by k0shk0sh** [comment]
Idk, probably it was a bug in AS or something :D . thanks buddy. 👍

**Comment by thermatk** [comment]
aaah, that's what you mean
yes, you have to include multidex, it's still there
but you only had to include one line `multiDexEnabled true`, not the support dependency and extend the MultiDexApplication. That was overkill targeted at sdk<21

**Comment by thermatk** [comment]
Perfect!
One less dependency :+1:

**Comment by k0shk0sh** [comment]
Yup, sorry for buzzing the other PR, was testing :p and PullRequest reviews will be included in today's release :)

**Pull request merged**
