### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by cozyplanes**
a bit of grammar stuff fix, said by yakov116 in PR 1060

### CODE REVIEW

**Comment by yakov116** [comment]
@cozyplanes wait wait wait. Lets merge the other one first. I am going to make some changes :)

**Comment by cozyplanes** [comment]
haha, side note, dutch translation coming soon by my friend

**Comment by yakov116** [comment]
@cozyplanes now you can do this. Look at my changes

**Comment by cozyplanes** [comment]
@yakov116 going to sleep. sorry. coming back tomorrow.

**Comment by cozyplanes** [comment]
@yakov116 again, sorry but what changes did you made?

**Comment by yakov116** [comment]
@cozyplanes look in the other pulled request

**Comment by cozyplanes** [comment]
I am quite not sure what to fix. there ain't other PRs to look at, and I don't see any changes YOU made

**Comment by yakov116** [comment]
@cozyplanes #1060

**Comment by cozyplanes** [comment]
i will try to finish by this week release. i just got an urgent project request.

**Comment by k0shk0sh** [comment]
is this going to be ever completed? I don't like seeing things hanging.

**Comment by cozyplanes-development** [comment]
i will try to finish by today (8hrs)

**Comment by cozyplanes-development** [comment]
oh and i am cozyplanes too, second acc

**Comment by cozyplanes** [comment]
Ok, I apologize again, but I feel I can't finish this any time soon. Maybe end of this month.

@Astro36 Any thoughts helping me out? (smirk)

**Comment by yakov116** [comment]
@cozyplanes I'll do it after #1119 is merged

**Comment by yakov116** [comment]
@cozyplanes going to close this

**Comment by cozyplanes** [comment]
Thank you, and sorry again

**Pull request closed without merging**
