### PR TITLE
Add auth to all urls for download manager

### LINKED ISSUE #1707: Suggestion: Add token to header
I don't know where you saw that github can't access private repo data, but you can authorize requests by either sending your token in the header or as a query argument. Given that you are using retrofit, it would probably be easiest to add an interceptor to pass a token from a shared pref or something. That way, if it changes, you won't need to make a new retrofit instance.

See api documentation (if you are still using v3): https://developer.github.com/v3/#authentication

This will also resolve #1387, #1330, #1185

I can also confirm that this is possible and not limited to browser cookies, because you can download private releases with OctoDroid

### PR DESCRIPTION
**Pull request by AllanWang**
Tested for compilation only. Resolves #1707

### CODE REVIEW

**Comment by AllanWang** [comment]
Tested the debug build and it doesn't seem to be working. Not sure if there are more places without authentication or if something is wrong with the token

**Comment by k0shk0sh** [comment]
There are none :(

**Comment by AllanWang** [comment]
@k0shk0sh I am now receiving api rate limit toast warnings for both the debug app and release app. How is that even possible?

**Comment by k0shk0sh** [comment]
Search api has limits ;). Search screen, my issues screen, my pulls screen, filter issues, prs and some other places I can't remember.

**Comment by AllanWang** [comment]
My bad. I noticed the rate limit is imposed on other apps as well. Probably had something to do with other tests I've made which are account related

**Comment by yakov116** [comment]
@k0shk0sh Were merging this?

**Comment by AllanWang** [comment]
No. This didn't seem to solve anything

**Comment by yakov116** [comment]
@AllanWang Ill merge it...

**Pull request merged**
