### PR TITLE
Improved Simplified Chinese (zh-CN) translation

### PR DESCRIPTION
**Pull request by f0rb1d**
Improved Simplified Chinese (zh-CN) translation

### CODE REVIEW

**Comment by k0shk0sh** [comment]
```
values-zh-rCN/strings.xml:493:27: Error: The entity name must immediately follow the '&' in the entity reference.
```

**Comment by f0rb1d** [comment]
fixed now

**Comment by k0shk0sh** [comment]
still same probs :)

**Comment by yakov116** [comment]
@f0rb1d I removed one of the FAQ lines double check that all is ok

**Pull request merged**
