### PR TITLE
Improved Russian translation

### PR DESCRIPTION
**Pull request by dedepete**
A bunch of improvements with new translated strings.

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Thanks man :)

**Comment by yakov116** [comment]
f you have an XDA profile i can link it for the Language Contributors

**Comment by dedepete** [comment]
Unfortunately, I am not registered there.

**Comment by k0shk0sh** [comment]
@dedepete sorry about that, It just its hard for me to track everything, tbh I expect who contributes to language, should actually include themselves to the list. 
I'm sorry about that & going to commit in awhile adding that.

**Comment by k0shk0sh** [comment]
@dedepete sorry about my previous comment, I understand it wrong lol.

**Pull request merged**
