### PR TITLE
Add OTP code

### PR DESCRIPTION
**Pull request by alorma**
Hi @k0shk0sh 

I've implemented the OTP (2fa) code.

But now i encountered a problem with the token, maybe you can take a look on it:

https://developer.github.com/changes/2014-12-08-removing-authorizations-token/

> I've updated the login card color, now uses `colorAccent` and is more visual :P

screenshot_1489322604

### CODE REVIEW

**Comment by alorma** [comment]
I guess you should implement this way: https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization /with POST request to `/authorizations`

**Comment by k0shk0sh** [comment]
@alorma Alright I will check on it once I'm back home. thank you for the quick pr. btw: the header looks way better than what I did for the login screen 😀

**Comment by alorma** [comment]
I add a [WIP] here, i will check

**Comment by alorma** [comment]
Fixed! Now it logins :D

**Comment by k0shk0sh** [comment]
wohoo, that's quick man, salute 🖖. thank you very much when I get back home, merge fix another thing and release immediately. 
thank you again.

**Pull request merged**
