### PR TITLE
Improved german translation again

### PR DESCRIPTION
**Pull request by failex234**

### CODE REVIEW

**Comment by k0shk0sh** [comment]
Hey, Felix thanks for your update :) , the problem with FastHub is that it isn't 100% finished, so they will be more phrases that needs translating. I hope that isn't a bother for you.

**Comment by alamo18** [comment]
nuuuuu the previous icon was so much better

**Comment by k0shk0sh** [comment]
@alamo18 it was :'( . I guess we need new icon :'(

**Comment by alamo18** [comment]
the icon was perfectly fine it didn't harm anyone nor impersonate at all screw you gplay automated bot thing

**Comment by alamo18** [comment]
@k0shk0sh you rock

maybe one day when i have enough java experience ill chip in

**Comment by failex234** [comment]
I will keep translating forever hopefully :P

**Comment by k0shk0sh** [comment]
@alamo18 you are welcome at any time :) 
Thanks

**Comment by k0shk0sh** [comment]
@failex234 thanks man :)

**Pull request merged**
