### PR TITLE
Improved app strings

### PR DESCRIPTION
**Pull request by HeinrichReimer**
Improved punctuation, wrong uppercase/lowercase, made internal strings not translatable, removed string dependencies to `@android:` strings to prevent inconsistent translations​, simplified some strings, added TODOs where string concatenation is used instead of string format args.

### Things we need to think about:
- **Make settings stateful:**  
E.g. instead of having a toggle to disable list animations, add descriptions like _"Enable list animations"_ and _"Disable list animations"_ that correspond to the actual current setting. (I guess in XML it is `summaryOn`/`summaryOff` or something similar). Then of course if list animations are enabled, the toggle should be **on** .(Android has a default attribute for preference XMLs.)
- **Name and sort strings in XML file:**  
Having them sorted in categories like _Settings_, _Markdown editor_, ... and having them being named in a consistent scheme like `<string name="[type]_[category](_[subcategory])_[name](_[state])"></string>` where `[type]` is one of `title`/`description`/`label`/..., `[category]` is the category the string is listed under, `[subcategory]` is an optional subcategory if needed, `[name]` is a descriptive short name (unique in the category) and `[state]` is an optional state for things like on/of or enabled/disabled. This way translators and contributors can better see where and why the string is used and can contribute more easily.

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
@Rainer-Lang they could, but if you use the Android strings that can lead to situations where _"OK"_ and _"Cancel"_ are translated to the local language but the rest of the app isn't which looks very odd and can confuse users. I've had these issues in an app I made and people complained that they'd rather use an app that's fully English than an app where just _"OK"_ and _"Cancel"_ are translated.

**Comment by Rainer-Lang** [comment]
Understand, thanks.

**Comment by k0shk0sh** [comment]
nice, someone seems to be done with his vacation 😀. Will merge this after work.
thanks

**Comment by HeinrichReimer** [comment]
@k0shk0sh yeah, I'm traveling home right now. will try to clone the repo tomorrow

**Comment by k0shk0sh** [comment]
@HeinrichReimer cool, can't wait :)

**Pull request merged**
