### PR TITLE
Added unfinished Korean translations

### PR DESCRIPTION
**Pull request by cozyplanes**
Worked in some translations that weren't finished.

`Banner` translation not done yet.

### CODE REVIEW

**Comment by cozyplanes** [comment]
It seems that appveyor ci always fails in translation update @k0shk0sh

**Comment by k0shk0sh** [comment]
@cozyplanes it will be removed at all. So ignore it.

**Comment by cozyplanes** [comment]
so... any merge thoughts?

**Comment by k0shk0sh** [comment]
@cozyplanes I'm at work so no merge until I finish work or @yakov116 is awake

**Comment by yakov116** [comment]
@k0shk0sh @cozyplanes looks good merging

**Comment by rancidfrog** [comment]
Some projects use weblate for translations.
see weblateorg

**Pull request merged**
