### PR TITLE
fixed #833

### LINKED ISSUE #833: Jerky scrolling through README
**FastHub Version:**  4.0.3
**Android Version:**  7.1.2 (official LineageOS 14.1)
**Device Information:**  
- MANUFACTURER: Xiaomi
- BRAND: Xiaomi
- MODEL: Mi5
---

I'm having issues with scrolling while reading the README. The menus on the top and bottom keep popping up and down erratically, creating a very unpleasant scrolling experience, even though I'm making very smooth scrolling motions. It happens on any README that I could find.

Here are 2 videos of it happening [with AOSP WebView that comes with LineageOS](https://streamable.com/80wij) and [with Google WebView from the Play Store.](https://streamable.com/ilvpd)
As you can see, the results are identical. 

Starting with a completely fresh install didn't help. Changing the display and font size in system settings to default didn't help.

### LINKED ISSUE #858: Scrolling animation on repo view
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: OnePlus
- BRAND: OnePlus  
- MODEL: ONEPLUS A3003  
---

 Hi, I don't know what is causing this but there is a rather annoying scrolling/panel hiding animation on the repo view. I know it's not a bug _per se_, but maybe it's fixable.

[Thumb](https://youtu.be/Xz0q8eZbiG)

### LINKED ISSUE #863: Actionbar auto hide feature could be implemented better
**FastHub Version: 4.0.3**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- MANUFACTURER: Google
- BRAND: google  
- MODEL: Pixel  
---

Hello. Thanks for listening to my feedback. I wanted to raise a point about the auto hiding feature of the action bar as I find it really frustrating to use.

I find it frustrating because the screen jumps around when you slowing scroll the page down/up. I wonder if you might be able to mimick the way Twitter app handles the hiding of its actionbar as it feels much less jarring.

Many thanks for a great app!

### PR DESCRIPTION
**Pull request by TheAndroidMaster**
fixed #858 fixed #833 and fixed #863

### CODE REVIEW

**Comment by TheAndroidMaster** [comment]
NEVERMIND IT'S NOT FIXED DON'T APPROVE

**Comment by yakov116** [comment]
@TheAndroidMaster

**Comment by yakov116** [comment]
@TheAndroidMaster try the revamping timeline build and see if you still have it

**Comment by TheAndroidMaster** [comment]
Okay, _NOW_ it works properly. Fixed in 319dbaa

**Comment by yakov116** [comment]
@TheAndroidMaster thanks I test and its good!

**Pull request merged**
